# Generated by Django 5.2.1 on 2026-02-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_iv_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, help_text='Encrypted file binary (AES-GCM-256 ciphertext)', null=True, upload_to='encrypted_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, help_text='Display name shown to users (original filename)', max_length=255, null=True),
        ),
    ]
