# Generated by Django 5.2.1 on 2026-02-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_is_delivered'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_receive_e07cea_idx',
            old_name='msg_rcv_delivered_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_receive_5b2f13_idx',
            old_name='msg_rcv_read_idx',
        ),
    ]
