# Generated by Django 5.2.11 on 2026-02-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_rename_msg_rcv_delivered_idx_messaging_m_receive_e07cea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_encrypted_key',
            field=models.TextField(blank=True, default='', help_text='AES key wrapped with sender RSA-OAEP-4096 public key (base64)'),
        ),
    ]
