# Generated by Django 5.2.14 on 2026-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='moments/songs/'),
        ),
        migrations.AddField(
            model_name='moment',
            name='spotify_track_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='moment',
            name='spotify_track_info',
            field=models.JSONField(blank=True, help_text='Caches title, artist, and album art for faster loading', null=True),
        ),
    ]
