# Generated by Django 5.2.14 on 2026-05-29 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_moment_song_file_moment_spotify_track_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_moments', to=settings.AUTH_USER_MODEL),
        ),
    ]
