# Generated by Django 5.2.14 on 2026-05-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_moment_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='reactions',
            field=models.JSONField(blank=True, default=list, help_text="List of user reactions: [{'user_id', 'username', 'avatar', 'emoji', 'timestamp'}]", null=True),
        ),
    ]
