# Generated by Django 5.2.14 on 2026-05-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_moment_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replied_moment',
            field=models.ForeignKey(blank=True, help_text='If this message is a reply to a moment, stores a reference to it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.moment'),
        ),
    ]
