# Generated by Django 5.2.14 on 2026-05-29 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


from datetime import timedelta

def set_default_expiration(apps, schema_editor):
    Message = apps.get_model('messaging', 'Message')
    for msg in Message.objects.all():
        msg.expires_at = msg.timestamp + timedelta(days=7)
        msg.save(update_fields=['expires_at'])

class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_message_replied_moment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(set_default_expiration),
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.IntegerField(choices=[(1, '1 Day'), (7, '1 Week'), (30, '1 Month'), (180, '6 Months')], default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user1', 'user2'], name='messaging_c_user1_i_b2d695_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
