# Generated by Django 5.2.14 on 2026-05-30 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_group_groupmembership_groupmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='messaging.groupmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_group_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Message Read Receipt',
                'verbose_name_plural': 'Group Message Read Receipts',
                'indexes': [models.Index(fields=['message', 'user'], name='messaging_g_message_2b030c_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
