# Generated by Django 5.2.14 on 2026-06-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0017_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='cleared_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user last cleared the group chat.', null=True),
        ),
    ]
