# Generated by Django 5.2.14 on 2026-06-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0018_groupmembership_cleared_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='retention_days',
            field=models.IntegerField(choices=[(2, '2 Days'), (30, '1 Month'), (180, '6 Months')], default=2),
        ),
    ]
