# Generated by Django 5.2.14 on 2026-06-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0019_alter_chatsetting_retention_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='retention_days',
            field=models.IntegerField(choices=[(2, '2 Days'), (7, '1 Week'), (30, '1 Month'), (180, '6 Months')], default=2),
        ),
    ]
