# Generated by Django 5.2.14 on 2026-06-14 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0020_alter_chatsetting_retention_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoWishEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('custom', 'Custom')], default='birthday', max_length=20)),
                ('event_date', models.DateField()),
                ('language_preference', models.CharField(choices=[('english', 'English'), ('hinglish', 'Hinglish')], default='english', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_wish_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto Wish Event',
                'verbose_name_plural': 'Auto Wish Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoWishMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_wish_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto Wish Message',
                'verbose_name_plural': 'Auto Wish Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
