# Generated by Django 5.2.14 on 2026-06-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0022_autowishevent_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='autowishevent',
            name='custom_event_name',
            field=models.CharField(blank=True, help_text='Used when event_type is Custom', max_length=100, null=True),
        ),
    ]
