# Generated by Django 5.2.14 on 2026-06-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0023_autowishevent_custom_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='autowishevent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autowishevent',
            name='scheduled_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
