# Generated by Django 5.2.17 on 2026-09-07 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0025_chatlock_usersecuritycredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentPrivacySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_type', models.CharField(choices=[('all', 'My Contacts'), ('exclude', 'My Contacts Except...'), ('only', 'Only Share With...')], default='all', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moment Privacy Setting',
                'verbose_name_plural': 'Moment Privacy Settings',
            },
        ),
        migrations.RenameIndex(
            model_name='chatlock',
            new_name='messaging_c_user_id_d24ff1_idx',
            old_name='messaging_c_user_id_41a8db_idx',
        ),
        migrations.RenameIndex(
            model_name='chatlock',
            new_name='messaging_c_user_id_f37dcf_idx',
            old_name='messaging_c_user_id_b0f19c_idx',
        ),
        migrations.AddField(
            model_name='moment',
            name='privacy_type',
            field=models.CharField(choices=[('all', 'My Contacts'), ('exclude', 'My Contacts Except...'), ('only', 'Only Share With...')], db_index=True, default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='moment',
            name='privacy_users',
            field=models.ManyToManyField(blank=True, help_text="Excluded users if 'exclude', or allowed users if 'only'", related_name='targeted_moments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='momentprivacysetting',
            name='custom_users',
            field=models.ManyToManyField(blank=True, help_text='Default excluded users or allowed users', related_name='default_moment_privacy_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='momentprivacysetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moment_privacy_setting', to=settings.AUTH_USER_MODEL),
        ),
    ]
