# Generated by Django 5.2.17 on 2026-09-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0026_momentprivacysetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='retention_days',
            field=models.IntegerField(choices=[(2, '2 Days'), (7, '1 Week'), (30, '1 Month')], default=2),
        ),
    ]
