# Generated by Django 5.2.17 on 2026-09-16 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0030_message_delivered_at_message_read_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('group_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starred_by_users', to='messaging.groupmessage')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starred_by_users', to='messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Starred Message',
                'verbose_name_plural': 'Starred Messages',
                'indexes': [models.Index(fields=['user', 'created_at'], name='messaging_s_user_id_201400_idx'), models.Index(fields=['user', 'message'], name='messaging_s_user_id_01c0a2_idx'), models.Index(fields=['user', 'group_message'], name='messaging_s_user_id_51b574_idx')],
            },
        ),
    ]
