# Generated by Django 5.2.11 on 2026-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the account was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active_account',
            field=models.BooleanField(default=True, help_text='False = account soft-deleted by owner.'),
        ),
    ]
