# Generated by Django 5.2.14 on 2026-05-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's verified phone number with country code", max_length=20, null=True, unique=True),
        ),
    ]
