# Generated by Django 5.2.17 on 2026-09-08 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'My Contacts'), ('nobody', 'Nobody')], default='everyone', help_text='Controls who can view your last seen timestamp.', max_length=20)),
                ('online_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('same_as_last_seen', 'Same as Last Seen')], default='everyone', help_text='Controls who can view when you are actively online.', max_length=20)),
                ('read_receipts_enabled', models.BooleanField(default=True, help_text='Send and receive read receipts in 1-on-1 chats.')),
                ('media_upload_quality', models.CharField(choices=[('standard', 'Standard Quality'), ('hd', 'High Definition (HD)')], default='standard', help_text='Quality of media uploaded in conversations.', max_length=20)),
                ('media_auto_download', models.CharField(choices=[('all', 'Wi-Fi & Cellular'), ('wifi', 'Wi-Fi Only'), ('never', 'Never')], default='all', help_text='Network conditions under which media is automatically downloaded.', max_length=20)),
                ('message_sound_enabled', models.BooleanField(default=True, help_text='Play audio chimes for incoming and sent messages.')),
                ('enter_is_send', models.BooleanField(default=True, help_text='Pressing Enter key sends the message immediately.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
